"""add is_active column to User

Revision ID: ab8f63ed6513
Revises: bd3381a39185
Create Date: 2025-10-07 15:12:13.175667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8f63ed6513'
down_revision: Union[str, Sequence[str], None] = 'bd3381a39185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_id'), table_name='phone')
    op.drop_index(op.f('ix_phone_name'), table_name='phone')
    op.drop_table('phone')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_rescane', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isinstance', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ok', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('new', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_new', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('phone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('phone_pkey'))
    )
    op.create_index(op.f('ix_phone_name'), 'phone', ['name'], unique=False)
    op.create_index(op.f('ix_phone_id'), 'phone', ['id'], unique=False)
    # ### end Alembic commands ###
