"""create users table

Revision ID: 210dedc822db
Revises: e35588666e7e
Create Date: 2026-01-21 16:44:48.580742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210dedc822db'
down_revision: Union[str, Sequence[str], None] = 'e35588666e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_auth', sa.Column('session_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_user_auth_username'), table_name='user_auth')
    op.create_index(op.f('ix_user_auth_username'), 'user_auth', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_username'), table_name='user_auth')
    op.create_index(op.f('ix_user_auth_username'), 'user_auth', ['username'], unique=True)
    op.drop_column('user_auth', 'session_id')
    # ### end Alembic commands ###
