"""lod  table update

Revision ID: 2e3281975281
Revises: d27d074fb4ad
Create Date: 2026-01-26 16:51:16.961168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e3281975281'
down_revision: Union[str, Sequence[str], None] = 'd27d074fb4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_logs', sa.Column('response', sa.TEXT(), nullable=True))
    op.add_column('server_logs', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('server_logs', 'session_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server_logs', 'session_id',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('server_logs', 'is_verified')
    op.drop_column('server_logs', 'response')
    # ### end Alembic commands ###
