"""create users table

Revision ID: 7db7bd00b1d5
Revises: e74377a7c38d
Create Date: 2026-01-21 17:09:20.628875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db7bd00b1d5'
down_revision: Union[str, Sequence[str], None] = 'e74377a7c38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=10), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_ip', sa.String(length=255), nullable=True),
    sa.Column('api_method', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=100), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_logs_id'), 'server_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_logs_id'), table_name='server_logs')
    op.drop_table('server_logs')
    # ### end Alembic commands ###
