version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_auth_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: fastapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nero_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
